name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # here convert the git repository name to lowercase
      - name: Convert repo name to lowercase
        id: lowercase
        run: echo "repo_name_lc=${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.repo_name_lc }}:tagname